### ISSUE TITLE
Application no longer in AWS Serverless Application Repo

### ISSUE THREAD

**Issue by cmachler-sans** [symphoniacloud/code-pipeline-slack-notifier#10]
Is the application no longer on the AWS Serverless Application Repo? The link in the [documentation ](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:392967531616:applications~CodePipelineSlackNotifier) returns the application can't be found.

**Comment by mikebroberts** [comment]
Hi Chris - thanks for pointing that out! It's now available again. For some strange reason it had been flipped to being a "private" SAR.

In case you're interested, _in theory_ this should largely be replaced by https://aws.amazon.com/blogs/devops/introducing-aws-chatbot-chatops-for-aws/ . I tried using that right after it was first announced, and didn't have too much luck. But until then please feel free to use my SAR!

Cheers

Mike
