### ISSUE TITLE
does the notifier support other type of changes?

### ISSUE THREAD

**Issue by AlexSun98** [symphoniacloud/code-pipeline-slack-notifier#5]
Does the slack notifier support below state changes?
CodePipeline Action Execution State Change,
CodePipeline Stage Execution State Change

**Comment by mikebroberts** [comment]
Hi Alex - yes, if you modify the sam.yml file yourself. See the "Possible extensions / modifications" section in the README.

**Comment by mikebroberts** [comment]
This project is now deprecated - new Chatbot replacement SAR at https://github.com/symphoniacloud/codepipeline-chatbot
